channels:
  - conda-forge
  - bioconda
dependencies:
  - jupyterlab
  - seaborn
  - matplotlib
  - geopandas
  - pandas
  - r-base=4.2.2
  - snakemake
  - statannotations
  - r-phangorn
  - r-ggplot2
  - r-gridextra
  - r-caret
  - r-rocr
  - geoplot
  - matplotlib-scalebar
  - pysal
  - esda
